apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: securityheaders
  namespace: traefik

spec:
  headers:
    stsPreload: "true"
    stsIncludeSubdomains: "true"
    stsSeconds: 31536000    
    forceSTSHeader: "true" 
    frameDeny: "true"
    sslRedirect: "true"
  redirectScheme:
    scheme: https
