---
apiVersion: v1
kind: Service
metadata:
  name: traefik
  namespace: traefik

spec:
  ports:
  - protocol: TCP
    name: web
    port: 80
  - protocol: TCP
    name: admin
    port: 8080
  - protocol: TCP
    name: websecure
    port: 443
  selector:
    app: traefik
  type: LoadBalancer
---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: traefik
  name: traefik-ingress-controller
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: traefik-dynamic
  namespace: traefik
data:
  traefik-dynamic.yaml: |
    http:
      routers:
        https-redirect-all:
          rule: HostRegexp(`{host:.*}`)
          service: noop
          entryPoints:
          - web
          middlewares:
          - https-redirect
      services:
        noop:
          loadBalancer:
            servers:
            - url: ""
      middlewares:
        https-redirect:
          redirectScheme:
            scheme: https
            permanent: true
---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  namespace: traefik
  name: traefik
  labels:
    app: traefik
  annotations:
    fluxcd.io/automated: true
    fluxcd.io/tag.traefik: semver:~2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: traefik
  template:
    metadata:
      labels:
        app: traefik
    spec:
      serviceAccountName: traefik-ingress-controller
      containers:
      - name: traefik
        image: traefik:v2.0.4
        args:
        - --api.insecure
        - --serversTransport.insecureSkipVerify=true
        - --accesslog
        - --ping=true
        - --entrypoints.web.Address=:80
        - --entrypoints.websecure.Address=:443
        - --providers.kubernetescrd
        - --certificatesresolvers.default.acme.tlschallenge
        - --certificatesresolvers.default.acme.email=mikaelec+github@gmail.com
        - --certificatesresolvers.default.acme.storage=acme.json
        - --providers.file.filename=/config/traefik-dynamic.yaml
        volumeMounts:
        - name: config
          mountPath: "/config"
          readOnly: true
        ports:
        - name: web
          containerPort: 80
        - name: websecure
          containerPort: 443
        - name: admin
          containerPort: 8080
      volumes:
      - name: config
        configMap:
          name: traefik-dynamic
