---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: kibana
  namespace: elastic
  annotations:
    fluxcd.io/automated: "true"
    repository.fluxcd.io/kibana: image
    tag.fluxcd.io/kibana: imageTag
    filter.fluxcd.io/kibana: semver:~7.4
spec:
  releaseName: kibana
  chart:
    repository: https://helm.elastic.co
    name: kibana
    version: 7.4.0
  values:
    image: docker.elastic.co/kibana/kibana
    imageTag: 7.4.1
    elasticsearchHosts: "https://elasticsearch-master:9200"
    extraEnvs:
      - name: 'ELASTICSEARCH_USERNAME'
        valueFrom:
          secretKeyRef:
            name: elastic-credentials
            key: username
      - name: 'ELASTICSEARCH_PASSWORD'
        valueFrom:
          secretKeyRef:
            name: elastic-credentials
            key: password
      - name: 'KIBANA_ENCRYPTION_KEY'
        valueFrom:
          secretKeyRef:
            name: kibana
            key: encryptionkey

    kibanaConfig:
      kibana.yml: |
        server.ssl:
          enabled: true
          key: /usr/share/kibana/config/certs/elastic-certificate.pem
          certificate: /usr/share/kibana/config/certs/elastic-certificate.pem
        xpack.security.encryptionKey: ${KIBANA_ENCRYPTION_KEY}
        elasticsearch.ssl:
          certificateAuthorities: /usr/share/kibana/config/certs/elastic-certificate.pem
          verificationMode: certificate

    protocol: https

    secretMounts:
      - name: elastic-certificate-pem
        secretName: elastic-certificate-pem
        path: /usr/share/kibana/config/certs

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: ingress-kibana
  namespace: elastic
spec:
  entryPoints:
    - websecure
  routes:
  - match: Host(`kibana.k8s.mikelk.dk`)
    kind: Rule
    services:
    - name: kibana-kibana
      port: 5601
      scheme: https
    middlewares:
    - name: securityheaders
      namespace: traefik
  tls:
    certResolver: default
    options:
      name: default
      namespace: traefik
